name: 'PR Validation'
on:
  pull_request_target: 
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pre-validation:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/pr_checks.yml@4ed58e98db3507ec026d9ed167705ca298f78a50 # pinned to latest
    secrets: inherit
    with:
      subjectPattern: '^.+$'